### ISSUE TITLE
Uncaught Error: Extension context invalidated.

### ISSUE THREAD

**Issue by maldovar1024** [CLDXiang/huiyou.js#33]
关闭扩展或重新载入时，由于注入的脚本失去了与后台的连接，会触发 Uncaught Error: Extension context invalidated.
https://stackoverflow.com/questions/53939205/how-to-avoid-extension-context-invalidated-errors-when-messaging-after-an-exte

**Comment by CLDXiang** [comment]
这个是正常的吧？Chrome 层面的问题
